// RAG Namespace Storage
// This file stores the namespace used for RAG embeddings
// Auto-generated by trainModel - DO NOT EDIT MANUALLY

module.exports = {
  namespace: 'default',
  indexName: 'recruit-project',
  lastUpdated: '2025-11-19T06:35:14.823Z'
};
